# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/csvw-pandas-integration',
                'doc_host': 'https://charlesvardeman.github.io',
                'git_url': 'https://github.com/charlesvardeman/csvw-pandas-integration',
                'lib_path': 'csvw_pandas_integration'},
  'syms': {'csvw_pandas_integration.core': {'csvw_pandas_integration.core.foo': ('core.html#foo', 'csvw_pandas_integration/core.py')}}}