ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "csvw-pandas-integration"
  site-url: "https://charlesvardeman.github.io/csvw-pandas-integration"
  description: "A Python package for seamlessly managing CSVW metadata in data analysis environments using pandas, nbdev, and dvc."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/charlesvardeman/csvw-pandas-integration"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/charlesvardeman/csvw-pandas-integration"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
